language: node_js

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test:e2e

before_install:
  - npm config set spin false
  - npm config set progress false
  - sudo apt-get -y install libfontconfig-dev

install:
  - npm install

before_script:
  - export DISPLAY=:99
  - sudo /etc/init.d/xvfb start
  - sleep 3
  - sudo /etc/init.d/openbox start
  - npm run build:prod

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
